import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    donate: "Donate",
    tagline: "Early Detection Saves Lives",
    
    // Hero Section
    heroTitle: "Your Partner in",
    heroTitleAccent: "Breast Health",
    heroDescription: "Empowering women with knowledge, support, and resources for early detection and comprehensive breast cancer care.",
    searchPlaceholder: "Search symptoms, tests, or breast cancer topics...",
    search: "Search",
    womenAffected: "Women affected",
    survivalRate: "5-year survival*",
    startScreening: "Start screening",
    
    // Thermal Imaging
    aiThermalTitle: "AI-Powered Thermal Imaging Screening",
    aiThermalDescription: "Upload a thermal image of your breast to detect early signs of abnormality using advanced machine learning technology.",
    howItWorks: "How does thermal imaging work?",
    uploadThermalImage: "Upload Thermal Image",
    dragDropText: "Drag & drop your thermal image here",
    supportedFormats: "Supported formats: JPG, PNG, TIFF",
    chooseFile: "Choose File",
    takePhoto: "Take Photo",
    privacyText: "Your images are processed securely & never stored without consent",
    aiAnalysisResults: "AI Analysis Results",
    noAbnormalities: "No Abnormalities Detected",
    suspiciousArea: "Suspicious Area Found",
    highRisk: "High Risk Detected",
    recommendations: "Recommendations:",
    bookScreening: "Book Screening",
    talkToExpert: "Talk to Expert",
    saveToReports: "Save to Medical Reports",
    uploadToBegin: "Upload a thermal image to begin AI analysis",
    disclaimer: "This AI screening tool is designed to assist with early detection but is not a substitute for professional medical diagnosis. Always consult with a qualified healthcare professional for proper medical evaluation and diagnosis.",
    
    // Navigation
    home: "Home",
    about: "About",
    resources: "Resources",
    support: "Support",
    aboutBreastCancer: "About Breast Cancer",
    donateMakeADifference: "Donate – Make a Difference",
    educationalHub: "Educational Hub",
    livingWithBreastCancer: "Living with Breast Cancer",
    preventionScreening: "Prevention & Screening",
    treatmentOptions: "Treatment Options",
    resourcesSupport: "Resources & Support",
    researchInnovation: "Research & Innovation",
    contactUs: "Contact Us",

    // About Breast Cancer Page
    aboutBreastCancerTitle: "About Breast Cancer",
    aboutBreastCancerDescription: "Understanding breast cancer is the first step toward prevention, early detection, and effective treatment. Knowledge empowers you to make informed decisions about your health.",
    womenLifetimeRisk: "Women lifetime risk",
    fiveYearSurvivalEarly: "5-year survival when caught early",
    newCasesAnnually: "New cases annually worldwide",
    whatIsBreastCancer: "What is Breast Cancer?",
    breastCancerDefinition1: "Breast cancer occurs when cells in the breast tissue grow uncontrollably, forming a tumor that can be felt as a lump or seen on imaging tests.",
    breastCancerDefinition2: "There are different types of breast cancer, with some growing slowly and others spreading quickly. Early detection significantly improves treatment outcomes.",
    breastCancerDefinition3: "While breast cancer primarily affects women, it can also occur in men, though this is much less common.",
    learnMoreScreening: "Learn More About Screening",
    earlySignsTitle: "Early Signs & Symptoms",
    earlySignsDescription: "Being aware of these warning signs can help with early detection and better treatment outcomes.",
    lumpOrThickening: "Lump or Thickening",
    lumpDescription: "A new lump in the breast or underarm area that feels different from surrounding tissue.",
    skinChanges: "Skin Changes",
    skinChangesDescription: "Dimpling, puckering, or redness of the breast skin, resembling an orange peel texture.",
    nippleChanges: "Nipple Changes",
    nippleChangesDescription: "Inverted nipple, unusual discharge, or changes in nipple appearance or sensation.",
    breastSizeChanges: "Size/Shape Changes",
    breastSizeChangesDescription: "Unexplained changes in breast size, shape, or appearance that persist over time.",
    riskFactorsTitle: "Risk Factors",
    riskFactorsDescription: "While having risk factors doesn't mean you'll develop breast cancer, awareness helps guide prevention strategies.",
    ageRiskFactor: "Age - Risk increases with age, especially after 50",
    familyHistoryRiskFactor: "Family history of breast or ovarian cancer",
    geneticMutationsRiskFactor: "Genetic mutations (BRCA1, BRCA2, and others)",
    hormoneExposureRiskFactor: "Prolonged exposure to estrogen",
    lifestyleFactorsRiskFactor: "Lifestyle factors (alcohol, obesity, lack of exercise)",
    previousBreastCancerRiskFactor: "Previous breast cancer or certain breast conditions",
    whyAwarenessMatters: "Why Awareness Matters",
    awarenessImportanceText: "Early detection through awareness and regular screening can increase survival rates to over 99%. When caught early, breast cancer is highly treatable with various effective treatment options available.",
    scheduleScreening: "Schedule Screening",
    findSupportGroup: "Find Support Group",

    // Living with Breast Cancer Page
    livingWithBreastCancerTitle: "Living with Breast Cancer",
    livingWithBreastCancerDescription: "A breast cancer diagnosis doesn't define you. With the right support, lifestyle adjustments, and medical care, many people live full, meaningful lives during and after treatment.",
    lifestyleTipsTitle: "Healthy Lifestyle Tips",
    lifestyleTipsDescription: "Small changes in daily habits can make a significant difference in your overall well-being and treatment outcomes.",
    stayActiveTitle: "Stay Active",
    stayActiveDescription: "Regular, gentle exercise can help manage fatigue, improve mood, and maintain strength during treatment.",
    gentleExercise: "Gentle exercises like walking or swimming",
    walkingDaily: "Daily walks of 15-30 minutes",
    yogaStretching: "Yoga and gentle stretching",
    strengthTraining: "Light strength training (with doctor approval)",
    nutritionTitle: "Nutrition Focus",
    nutritionDescription: "Eating well helps your body cope with treatment and recover more effectively.",
    balancedDiet: "Balanced diet rich in fruits and vegetables",
    hydration: "Staying well-hydrated throughout the day",
    limitProcessedFoods: "Limiting processed and sugary foods",
    antioxidantRich: "Antioxidant-rich foods like berries and leafy greens",
    mentalHealthTitle: "Mental Health",
    mentalHealthDescription: "Taking care of your emotional well-being is just as important as physical care.",
    stressManagement: "Stress management techniques",
    meditationPractice: "Regular meditation or mindfulness practice",
    counselingSupport: "Professional counseling or therapy",
    socialConnections: "Maintaining social connections and hobbies",
    familySupportTitle: "Family Support",
    familySupportDescription: "Involving family members in your care journey can provide essential emotional and practical support.",
    openCommunication: "Open, honest communication about needs",
    shareResponsibilities: "Sharing household responsibilities",
    qualityTime: "Spending quality time together",
    professionalGuidance: "Family counseling if needed",
    copingStrategiesTitle: "Coping Strategies",
    copingStrategiesDescription: "Practical approaches to manage the emotional and physical challenges of breast cancer.",
    buildSupportNetwork: "Build a Support Network",
    supportNetworkDescription: "Connect with family, friends, support groups, and healthcare professionals.",
    maintainRoutine: "Maintain Daily Routines",
    routineDescription: "Keep familiar daily activities to provide stability and normalcy.",
    practiceGratitude: "Practice Gratitude",
    gratitudeDescription: "Focus on positive aspects of life, no matter how small they may seem.",
    setSmallGoals: "Set Small, Achievable Goals",
    smallGoalsDescription: "Break larger tasks into manageable steps to maintain a sense of accomplishment.",
    stayInformed: "Stay Informed but Not Overwhelmed",
    stayInformedDescription: "Learn about your condition but limit excessive research that may cause anxiety.",
    expressEmotions: "Express Your Emotions",
    expressEmotionsDescription: "Allow yourself to feel and express emotions through talking, writing, or creative outlets.",
    survivorStoriesTitle: "Survivor Stories",
    survivorStoriesDescription: "Real stories from brave women who have faced breast cancer and emerged stronger.",
    sarahStory: "After my diagnosis, I focused on staying positive and maintaining my exercise routine. The support from my family and medical team was incredible.",
    emilyStory: "Breast cancer taught me to appreciate every moment. I'm now an advocate for early detection and support others on their journey.",
    mariaStory: "The hardest part was the uncertainty, but taking it one day at a time helped me through treatment and recovery.",
    age: "Age",
    yearsStrong: "Years Strong",
    inspirationalMessageTitle: "You Are Not Alone",
    inspirationalMessage: "Every journey is unique, but you don't have to walk it alone. There are countless resources, support networks, and healthcare professionals ready to help you every step of the way.",
    joinSupportGroup: "Join Support Group",
    shareYourStory: "Share Your Story",
    additionalResourcesTitle: "Additional Resources",
    nutritionGuides: "Nutrition Guides",
    exercisePrograms: "Exercise Programs",
    mentalHealthSupport: "Mental Health Support",
    familyResources: "Family Resources",
    learnMore: "Learn More",

    // Prevention & Screening
    preventionScreeningTitle: "Prevention & Screening",
    preventionScreeningDescription: "Early detection saves lives. Regular screenings and preventive measures are your best defense against breast cancer.",
    regularScreenings: "Regular Screenings",
    regularScreeningsDescription: "Schedule mammograms and clinical exams as recommended by your healthcare provider.",
    selfExamination: "Self-Examination",
    selfExaminationDescription: "Learn proper self-examination techniques to detect changes early.",
    healthyLifestyle: "Healthy Lifestyle",
    healthyLifestyleDescription: "Maintain a healthy weight, exercise regularly, and limit alcohol consumption.",
    learnSelfExam: "Learn Self-Exam",
    lifestyleTips: "Lifestyle Tips",

    // Treatment Options
    treatmentOptionsTitle: "Treatment Options",
    treatmentOptionsDescription: "Modern breast cancer treatment offers many effective options, often used in combination for the best outcomes.",
    surgery: "Surgery",
    surgeryDescription: "Surgical removal of tumors, ranging from lumpectomy to mastectomy, depending on cancer stage and patient preference.",
    chemotherapy: "Chemotherapy",
    chemotherapyDescription: "Systemic treatment using medications to destroy cancer cells throughout the body.",
    radiation: "Radiation Therapy",
    radiationDescription: "High-energy beams target and destroy cancer cells in specific areas of the body.",
    targetedTherapy: "Targeted Therapy",
    targetedTherapyDescription: "Treatments that target specific cancer cell characteristics, often with fewer side effects.",

    // Resources & Support
    resourcesSupportTitle: "Resources & Support",
    resourcesSupportDescription: "Comprehensive support services to help you and your loved ones navigate the breast cancer journey.",
    helplines: "24/7 Helplines",
    helplinesDescription: "Round-the-clock emotional support and information from trained counselors.",
    supportGroups: "Support Groups",
    supportGroupsDescription: "Connect with others who understand your experience through local and online communities.",
    counseling: "Professional Counseling",
    counselingDescription: "Individual and family therapy to help cope with emotional challenges.",
    ngosSupport: "NGO Support",
    ngosSupportDescription: "Non-profit organizations providing financial assistance, resources, and advocacy.",
    getSupport: "Get Support",

    // Research & Innovation
    researchInnovationTitle: "Research & Innovation",
    researchInnovationDescription: "Cutting-edge research and technological advances are constantly improving breast cancer detection and treatment.",
    aiDetection: "AI in Detection",
    aiDetectionDescription: "Artificial intelligence is revolutionizing early detection through advanced imaging analysis.",
    latestStudies: "Latest Studies",
    latestStudiesDescription: "Ongoing clinical trials and research studies are developing new treatment approaches.",
    newTreatments: "New Treatments",
    newTreatmentsDescription: "Innovative therapies including immunotherapy and precision medicine are showing promising results.",
    clinicalTrials: "Clinical Trials",
    clinicalTrialsDescription: "Opportunities to access cutting-edge treatments through participation in research studies.",
    readMore: "Read More",

    // Contact Us
    contactUsTitle: "Contact Us",
    contactUsDescription: "We're here to help. Reach out to our team for support, information, or to connect with local resources.",
    getInTouch: "Get in Touch",
    helplineNumber: "Helpline Number",
    helplineDescription: "24/7 support for questions, concerns, and emotional support",
    emailSupport: "Email Support",
    emailDescription: "Send us your questions and we'll respond within 24 hours",
    centerLocations: "Help Centers",
    findNearestCenter: "Find Your Nearest Center",
    centerDescription: "Local support centers and partner hospitals in your area",
    operatingHours: "Operating Hours",
    hoursDescription: "Emergency support available around the clock",
    sendMessage: "Send Us a Message",
    formDescription: "Fill out the form below and our team will get back to you soon.",
    firstName: "First Name",
    firstNamePlaceholder: "Enter your first name",
    lastName: "Last Name",
    lastNamePlaceholder: "Enter your last name",
    emailAddress: "Email Address",
    emailPlaceholder: "Enter your email address",
    phoneNumber: "Phone Number",
    phonePlaceholder: "Enter your phone number",
    subject: "Subject",
    subjectPlaceholder: "What is this regarding?",
    message: "Message",
    messagePlaceholder: "Tell us how we can help you...",
  },
  es: {
    // Header
    donate: "Donar",
    tagline: "La Detección Temprana Salva Vidas",
    
    // Hero Section
    heroTitle: "Tu Compañero en",
    heroTitleAccent: "Salud Mamaria",
    heroDescription: "Empoderando a las mujeres con conocimiento, apoyo y recursos para la detección temprana y atención integral del cáncer de mama.",
    searchPlaceholder: "Buscar síntomas, pruebas o temas sobre cáncer de mama...",
    search: "Buscar",
    womenAffected: "Mujeres afectadas",
    survivalRate: "Supervivencia a 5 años*",
    startScreening: "Comenzar exámenes",
    
    // Thermal Imaging
    aiThermalTitle: "Detección con Imágenes Térmicas con IA",
    aiThermalDescription: "Sube una imagen térmica de tu pecho para detectar signos tempranos de anomalías usando tecnología de aprendizaje automático avanzada.",
    howItWorks: "¿Cómo funciona la imagen térmica?",
    uploadThermalImage: "Subir Imagen Térmica",
    dragDropText: "Arrastra y suelta tu imagen térmica aquí",
    supportedFormats: "Formatos compatibles: JPG, PNG, TIFF",
    chooseFile: "Elegir Archivo",
    takePhoto: "Tomar Foto",
    privacyText: "Tus imágenes se procesan de forma segura y nunca se almacenan sin consentimiento",
    aiAnalysisResults: "Resultados del Análisis de IA",
    noAbnormalities: "No se Detectaron Anomalías",
    suspiciousArea: "Área Sospechosa Encontrada",
    highRisk: "Alto Riesgo Detectado",
    recommendations: "Recomendaciones:",
    bookScreening: "Programar Examen",
    talkToExpert: "Hablar con Experto",
    saveToReports: "Guardar en Reportes",
    uploadToBegin: "Sube una imagen térmica para comenzar el análisis de IA",
    disclaimer: "Esta herramienta de detección de IA está diseñada para ayudar con la detección temprana pero no es un sustituto del diagnóstico médico profesional. Siempre consulta con un profesional de la salud calificado.",
    
    // Navigation
    home: "Inicio",
    about: "Acerca de",
    resources: "Recursos",
    support: "Apoyo",
    aboutBreastCancer: "Acerca del Cáncer de Mama",
    donateMakeADifference: "Donar – Hacer la Diferencia",
    educationalHub: "Centro Educativo",
    livingWithBreastCancer: "Viviendo con Cáncer de Mama",
    preventionScreening: "Prevención y Detección",
    treatmentOptions: "Opciones de Tratamiento",
    resourcesSupport: "Recursos y Apoyo",
    researchInnovation: "Investigación e Innovación",
    contactUs: "Contáctanos",

    // About Breast Cancer Page
    aboutBreastCancerTitle: "Acerca del Cáncer de Mama",
    aboutBreastCancerDescription: "Entender el cáncer de mama es el primer paso hacia la prevención, detección temprana y tratamiento efectivo.",
    womenLifetimeRisk: "Riesgo de por vida en mujeres",
    fiveYearSurvivalEarly: "Supervivencia a 5 años cuando se detecta temprano",
    newCasesAnnually: "Nuevos casos anuales mundialmente",
    whatIsBreastCancer: "¿Qué es el Cáncer de Mama?",
    breastCancerDefinition1: "El cáncer de mama ocurre cuando las células del tejido mamario crecen sin control, formando un tumor.",
    breastCancerDefinition2: "Hay diferentes tipos de cáncer de mama, algunos crecen lentamente y otros se extienden rápidamente.",
    breastCancerDefinition3: "Aunque el cáncer de mama afecta principalmente a mujeres, también puede ocurrir en hombres.",
    learnMoreScreening: "Más Sobre Detección",
    earlySignsTitle: "Signos y Síntomas Tempranos",
    earlySignsDescription: "Conocer estas señales de advertencia puede ayudar con la detección temprana.",
    lumpOrThickening: "Bulto o Engrosamiento",
    lumpDescription: "Un nuevo bulto en el pecho o área de la axila que se siente diferente.",
    skinChanges: "Cambios en la Piel",
    skinChangesDescription: "Hoyuelos, arrugas o enrojecimiento de la piel del pecho.",
    nippleChanges: "Cambios en el Pezón",
    nippleChangesDescription: "Pezón invertido, secreción inusual o cambios en la apariencia.",
    breastSizeChanges: "Cambios de Tamaño/Forma",
    breastSizeChangesDescription: "Cambios inexplicables en el tamaño, forma o apariencia del pecho.",
    riskFactorsTitle: "Factores de Riesgo",
    riskFactorsDescription: "Aunque tener factores de riesgo no significa que desarrollarás cáncer de mama, la conciencia ayuda.",
    ageRiskFactor: "Edad - El riesgo aumenta con la edad, especialmente después de los 50",
    familyHistoryRiskFactor: "Historia familiar de cáncer de mama u ovario",
    geneticMutationsRiskFactor: "Mutaciones genéticas (BRCA1, BRCA2 y otras)",
    hormoneExposureRiskFactor: "Exposición prolongada al estrógeno",
    lifestyleFactorsRiskFactor: "Factores de estilo de vida (alcohol, obesidad, falta de ejercicio)",
    previousBreastCancerRiskFactor: "Cáncer de mama previo o ciertas condiciones mamarias",
    whyAwarenessMatters: "Por Qué Importa la Conciencia",
    awarenessImportanceText: "La detección temprana puede aumentar las tasas de supervivencia a más del 99%.",
    scheduleScreening: "Programar Detección",
    findSupportGroup: "Encontrar Grupo de Apoyo",

    // Living with Breast Cancer Page
    livingWithBreastCancerTitle: "Viviendo con Cáncer de Mama",
    livingWithBreastCancerDescription: "Un diagnóstico de cáncer de mama no te define. Con el apoyo adecuado, muchas personas viven vidas plenas.",
    lifestyleTipsTitle: "Consejos de Estilo de Vida Saludable",
    lifestyleTipsDescription: "Pequeños cambios en los hábitos diarios pueden hacer una diferencia significativa.",
    stayActiveTitle: "Manténte Activa",
    stayActiveDescription: "El ejercicio regular y suave puede ayudar a manejar la fatiga y mejorar el estado de ánimo.",
    gentleExercise: "Ejercicios suaves como caminar o nadar",
    walkingDaily: "Caminatas diarias de 15-30 minutos",
    yogaStretching: "Yoga y estiramientos suaves",
    strengthTraining: "Entrenamiento de fuerza ligero (con aprobación médica)",
    nutritionTitle: "Enfoque Nutricional",
    nutritionDescription: "Comer bien ayuda a tu cuerpo a lidiar con el tratamiento y recuperarse más efectivamente.",
    balancedDiet: "Dieta balanceada rica en frutas y verduras",
    hydration: "Mantenerse bien hidratada durante el día",
    limitProcessedFoods: "Limitar alimentos procesados y azucarados",
    antioxidantRich: "Alimentos ricos en antioxidantes como bayas y verduras de hoja verde",
    mentalHealthTitle: "Salud Mental",
    mentalHealthDescription: "Cuidar tu bienestar emocional es tan importante como el cuidado físico.",
    stressManagement: "Técnicas de manejo del estrés",
    meditationPractice: "Práctica regular de meditación o mindfulness",
    counselingSupport: "Consejería profesional o terapia",
    socialConnections: "Mantener conexiones sociales y pasatiempos",
    familySupportTitle: "Apoyo Familiar",
    familySupportDescription: "Involucrar a los miembros de la familia puede proporcionar apoyo emocional esencial.",
    openCommunication: "Comunicación abierta y honesta sobre las necesidades",
    shareResponsibilities: "Compartir responsabilidades del hogar",
    qualityTime: "Pasar tiempo de calidad juntos",
    professionalGuidance: "Consejería familiar si es necesario",
    copingStrategiesTitle: "Estrategias de Afrontamiento",
    copingStrategiesDescription: "Enfoques prácticos para manejar los desafíos emocionales y físicos.",
    buildSupportNetwork: "Construir una Red de Apoyo",
    supportNetworkDescription: "Conectar con familia, amigos, grupos de apoyo y profesionales de la salud.",
    maintainRoutine: "Mantener Rutinas Diarias",
    routineDescription: "Mantener actividades diarias familiares para proporcionar estabilidad.",
    practiceGratitude: "Practicar la Gratitud",
    gratitudeDescription: "Enfocarse en aspectos positivos de la vida, sin importar cuán pequeños sean.",
    setSmallGoals: "Establecer Metas Pequeñas y Alcanzables",
    smallGoalsDescription: "Dividir tareas grandes en pasos manejables para mantener un sentido de logro.",
    stayInformed: "Mantenerse Informada pero No Abrumada",
    stayInformedDescription: "Aprender sobre tu condición pero limitar la investigación excesiva.",
    expressEmotions: "Expresar Tus Emociones",
    expressEmotionsDescription: "Permítete sentir y expresar emociones a través de hablar, escribir o salidas creativas.",
    survivorStoriesTitle: "Historias de Supervivientes",
    survivorStoriesDescription: "Historias reales de mujeres valientes que han enfrentado el cáncer de mama.",
    sarahStory: "Después de mi diagnóstico, me enfoqué en mantenerme positiva y mantener mi rutina de ejercicio.",
    emilyStory: "El cáncer de mama me enseñó a apreciar cada momento. Ahora soy defensora de la detección temprana.",
    mariaStory: "La parte más difícil fue la incertidumbre, pero tomarlo un día a la vez me ayudó.",
    age: "Edad",
    yearsStrong: "Años Fuerte",
    inspirationalMessageTitle: "No Estás Sola",
    inspirationalMessage: "Cada viaje es único, pero no tienes que caminar sola. Hay innumerables recursos disponibles.",
    joinSupportGroup: "Unirse a Grupo de Apoyo",
    shareYourStory: "Comparte Tu Historia",
    additionalResourcesTitle: "Recursos Adicionales",
    nutritionGuides: "Guías de Nutrición",
    exercisePrograms: "Programas de Ejercicio",
    mentalHealthSupport: "Apoyo de Salud Mental",
    familyResources: "Recursos Familiares",
    learnMore: "Aprende Más",

    // Prevention & Screening
    preventionScreeningTitle: "Prevención y Detección",
    preventionScreeningDescription: "La detección temprana salva vidas. Las evaluaciones regulares son tu mejor defensa.",
    regularScreenings: "Evaluaciones Regulares",
    regularScreeningsDescription: "Programa mamografías y exámenes clínicos según lo recomendado.",
    selfExamination: "Autoexamen",
    selfExaminationDescription: "Aprende técnicas adecuadas de autoexamen para detectar cambios temprano.",
    healthyLifestyle: "Estilo de Vida Saludable",
    healthyLifestyleDescription: "Mantén un peso saludable, haz ejercicio regularmente y limita el alcohol.",
    learnSelfExam: "Aprender Autoexamen",
    lifestyleTips: "Consejos de Estilo de Vida",

    // Treatment Options
    treatmentOptionsTitle: "Opciones de Tratamiento",
    treatmentOptionsDescription: "El tratamiento moderno del cáncer de mama ofrece muchas opciones efectivas.",
    surgery: "Cirugía",
    surgeryDescription: "Extirpación quirúrgica de tumores, desde lumpectomía hasta mastectomía.",
    chemotherapy: "Quimioterapia",
    chemotherapyDescription: "Tratamiento sistémico usando medicamentos para destruir células cancerosas.",
    radiation: "Radioterapia",
    radiationDescription: "Rayos de alta energía que apuntan y destruyen células cancerosas.",
    targetedTherapy: "Terapia Dirigida",
    targetedTherapyDescription: "Tratamientos que apuntan a características específicas de células cancerosas.",

    // Resources & Support
    resourcesSupportTitle: "Recursos y Apoyo",
    resourcesSupportDescription: "Servicios de apoyo integral para ayudarte a navegar el viaje del cáncer de mama.",
    helplines: "Líneas de Ayuda 24/7",
    helplinesDescription: "Apoyo emocional e información las 24 horas de consejeros capacitados.",
    supportGroups: "Grupos de Apoyo",
    supportGroupsDescription: "Conecta con otros que entienden tu experiencia a través de comunidades.",
    counseling: "Consejería Profesional",
    counselingDescription: "Terapia individual y familiar para ayudar a lidiar con desafíos emocionales.",
    ngosSupport: "Apoyo de ONGs",
    ngosSupportDescription: "Organizaciones sin fines de lucro que brindan asistencia financiera y recursos.",
    getSupport: "Obtener Apoyo",

    // Research & Innovation
    researchInnovationTitle: "Investigación e Innovación",
    researchInnovationDescription: "La investigación de vanguardia mejora constantemente la detección y el tratamiento.",
    aiDetection: "IA en Detección",
    aiDetectionDescription: "La inteligencia artificial revoluciona la detección temprana através del análisis avanzado.",
    latestStudies: "Últimos Estudios",
    latestStudiesDescription: "Ensayos clínicos y estudios de investigación desarrollan nuevos enfoques de tratamiento.",
    newTreatments: "Nuevos Tratamientos",
    newTreatmentsDescription: "Terapias innovadoras incluyendo inmunoterapia y medicina de precisión.",
    clinicalTrials: "Ensayos Clínicos",
    clinicalTrialsDescription: "Oportunidades de acceder a tratamientos de vanguardia a través de estudios.",
    readMore: "Leer Más",

    // Contact Us
    contactUsTitle: "Contáctanos",
    contactUsDescription: "Estamos aquí para ayudar. Contacta a nuestro equipo para apoyo e información.",
    getInTouch: "Ponte en Contacto",
    helplineNumber: "Número de Línea de Ayuda",
    helplineDescription: "Apoyo 24/7 para preguntas, preocupaciones y apoyo emocional",
    emailSupport: "Apoyo por Email",
    emailDescription: "Envíanos tus preguntas y responderemos dentro de 24 horas",
    centerLocations: "Centros de Ayuda",
    findNearestCenter: "Encuentra Tu Centro Más Cercano",
    centerDescription: "Centros de apoyo locales y hospitales asociados en tu área",
    operatingHours: "Horarios de Operación",
    hoursDescription: "Apoyo de emergencia disponible las 24 horas",
    sendMessage: "Envíanos un Mensaje",
    formDescription: "Completa el formulario y nuestro equipo te contactará pronto.",
    firstName: "Nombre",
    firstNamePlaceholder: "Ingresa tu nombre",
    lastName: "Apellido",
    lastNamePlaceholder: "Ingresa tu apellido",
    emailAddress: "Dirección de Email",
    emailPlaceholder: "Ingresa tu dirección de email",
    phoneNumber: "Número de Teléfono",
    phonePlaceholder: "Ingresa tu número de teléfono",
    subject: "Asunto",
    subjectPlaceholder: "¿Sobre qué es esto?",
    message: "Mensaje",
    messagePlaceholder: "Dinos cómo podemos ayudarte...",
  },
  fr: {
    // Header
    donate: "Faire un don",
    tagline: "La Détection Précoce Sauve des Vies",
    
    // Hero Section
    heroTitle: "Votre Partenaire en",
    heroTitleAccent: "Santé Mammaire",
    heroDescription: "Autonomiser les femmes avec des connaissances, un soutien et des ressources pour la détection précoce et les soins complets du cancer du sein.",
    searchPlaceholder: "Rechercher symptômes, tests ou sujets sur le cancer du sein...",
    search: "Rechercher",
    womenAffected: "Femmes touchées",
    survivalRate: "Survie à 5 ans*",
    startScreening: "Commencer le dépistage",
    
    // Thermal Imaging
    aiThermalTitle: "Dépistage par Imagerie Thermique IA",
    aiThermalDescription: "Téléchargez une image thermique de votre sein pour détecter les signes précoces d'anomalie en utilisant une technologie d'apprentissage automatique avancée.",
    howItWorks: "Comment fonctionne l'imagerie thermique?",
    uploadThermalImage: "Télécharger Image Thermique",
    dragDropText: "Glissez-déposez votre image thermique ici",
    supportedFormats: "Formats supportés: JPG, PNG, TIFF",
    chooseFile: "Choisir un Fichier",
    takePhoto: "Prendre une Photo",
    privacyText: "Vos images sont traitées en sécurité et jamais stockées sans consentement",
    aiAnalysisResults: "Résultats de l'Analyse IA",
    noAbnormalities: "Aucune Anomalie Détectée",
    suspiciousArea: "Zone Suspecte Trouvée",
    highRisk: "Risque Élevé Détecté",
    recommendations: "Recommandations:",
    bookScreening: "Réserver Dépistage",
    talkToExpert: "Parler à un Expert",
    saveToReports: "Sauvegarder aux Rapports",
    uploadToBegin: "Téléchargez une image thermique pour commencer l'analyse IA",
    disclaimer: "Cet outil de dépistage IA est conçu pour aider à la détection précoce mais ne remplace pas un diagnostic médical professionnel. Consultez toujours un professionnel de la santé qualifié.",
    
    // Navigation
    home: "Accueil",
    about: "À propos",
    resources: "Ressources",
    support: "Soutien",
    aboutBreastCancer: "À Propos du Cancer du Sein",
    donateMakeADifference: "Faire un Don – Faire la Différence",
    educationalHub: "Centre Éducatif",
    livingWithBreastCancer: "Vivre avec le Cancer du Sein",
    preventionScreening: "Prévention et Dépistage",
    treatmentOptions: "Options de Traitement",
    resourcesSupport: "Ressources et Soutien",
    researchInnovation: "Recherche et Innovation",
    contactUs: "Nous Contacter",

    // About Breast Cancer Page
    aboutBreastCancerTitle: "À Propos du Cancer du Sein",
    aboutBreastCancerDescription: "Comprendre le cancer du sein est la première étape vers la prévention et la détection précoce.",
    womenLifetimeRisk: "Risque à vie des femmes",
    fiveYearSurvivalEarly: "Survie à 5 ans quand détecté tôt",
    newCasesAnnually: "Nouveaux cas annuels mondialement",
    whatIsBreastCancer: "Qu'est-ce que le Cancer du Sein?",
    breastCancerDefinition1: "Le cancer du sein survient quand les cellules du tissu mammaire croissent de manière incontrôlée.",
    breastCancerDefinition2: "Il existe différents types de cancer du sein, certains grandissent lentement et d'autres se propagent rapidement.",
    breastCancerDefinition3: "Bien que le cancer du sein affecte principalement les femmes, il peut aussi survenir chez les hommes.",
    learnMoreScreening: "En Savoir Plus sur le Dépistage",
    earlySignsTitle: "Signes et Symptômes Précoces",
    earlySignsDescription: "Connaître ces signaux d'alarme peut aider à la détection précoce.",
    lumpOrThickening: "Masse ou Épaississement",
    lumpDescription: "Une nouvelle masse dans le sein ou la zone de l'aisselle qui se sent différente.",
    skinChanges: "Changements de Peau",
    skinChangesDescription: "Capitons, plissements ou rougeur de la peau du sein.",
    nippleChanges: "Changements du Mamelon",
    nippleChangesDescription: "Mamelon inversé, écoulement inhabituel ou changements d'apparence.",
    breastSizeChanges: "Changements de Taille/Forme",
    breastSizeChangesDescription: "Changements inexpliqués de la taille, forme ou apparence du sein.",
    riskFactorsTitle: "Facteurs de Risque",
    riskFactorsDescription: "Avoir des facteurs de risque ne signifie pas que vous développerez un cancer du sein.",
    ageRiskFactor: "Âge - Le risque augmente avec l'âge, surtout après 50 ans",
    familyHistoryRiskFactor: "Antécédents familiaux de cancer du sein ou des ovaires",
    geneticMutationsRiskFactor: "Mutations génétiques (BRCA1, BRCA2 et autres)",
    hormoneExposureRiskFactor: "Exposition prolongée aux œstrogènes",
    lifestyleFactorsRiskFactor: "Facteurs de style de vie (alcool, obésité, manque d'exercice)",
    previousBreastCancerRiskFactor: "Cancer du sein antérieur ou certaines conditions mammaires",
    whyAwarenessMatters: "Pourquoi la Sensibilisation Importe",
    awarenessImportanceText: "La détection précoce peut augmenter les taux de survie à plus de 99%.",
    scheduleScreening: "Programmer un Dépistage",
    findSupportGroup: "Trouver un Groupe de Soutien",

    // Additional basic translations for other sections
    livingWithBreastCancerTitle: "Vivre avec le Cancer du Sein",
    livingWithBreastCancerDescription: "Un diagnostic de cancer du sein ne vous définit pas.",
    preventionScreeningTitle: "Prévention et Dépistage",
    preventionScreeningDescription: "La détection précoce sauve des vies.",
    treatmentOptionsTitle: "Options de Traitement",
    treatmentOptionsDescription: "Le traitement moderne offre de nombreuses options efficaces.",
    resourcesSupportTitle: "Ressources et Soutien",
    resourcesSupportDescription: "Services de soutien complets pour vous aider.",
    researchInnovationTitle: "Recherche et Innovation",
    researchInnovationDescription: "La recherche de pointe améliore constamment la détection.",
    contactUsTitle: "Nous Contacter",
    contactUsDescription: "Nous sommes là pour vous aider.",
    learnMore: "En Savoir Plus",
    getSupport: "Obtenir du Soutien",
    readMore: "Lire Plus",
    scheduleScreening: "Programmer un Dépistage",
    sendMessage: "Envoyer un Message",
  },
  de: {
    // Header
    donate: "Spenden",
    tagline: "Früherkennung Rettet Leben",
    
    // Hero Section
    heroTitle: "Ihr Partner für",
    heroTitleAccent: "Brustgesundheit",
    heroDescription: "Frauen mit Wissen, Unterstützung und Ressourcen für Früherkennung und umfassende Brustkrebsbetreuung stärken.",
    searchPlaceholder: "Symptome, Tests oder Brustkrebsthemen suchen...",
    search: "Suchen",
    womenAffected: "Betroffene Frauen",
    survivalRate: "5-Jahres-Überlebensrate*",
    startScreening: "Vorsorge beginnen",
    
    // Thermal Imaging
    aiThermalTitle: "KI-Gestützte Thermische Bildgebung",
    aiThermalDescription: "Laden Sie ein thermisches Bild Ihrer Brust hoch, um frühe Anzeichen von Anomalien mit fortschrittlicher maschineller Lerntechnologie zu erkennen.",
    howItWorks: "Wie funktioniert thermische Bildgebung?",
    uploadThermalImage: "Thermisches Bild Hochladen",
    dragDropText: "Ziehen Sie Ihr thermisches Bild hierher",
    supportedFormats: "Unterstützte Formate: JPG, PNG, TIFF",
    chooseFile: "Datei Wählen",
    takePhoto: "Foto Aufnehmen",
    privacyText: "Ihre Bilder werden sicher verarbeitet und niemals ohne Zustimmung gespeichert",
    aiAnalysisResults: "KI-Analyseergebnisse",
    noAbnormalities: "Keine Anomalien Erkannt",
    suspiciousArea: "Verdächtiger Bereich Gefunden",
    highRisk: "Hohes Risiko Erkannt",
    recommendations: "Empfehlungen:",
    bookScreening: "Vorsorge Buchen",
    talkToExpert: "Mit Experten Sprechen",
    saveToReports: "In Berichten Speichern",
    uploadToBegin: "Laden Sie ein thermisches Bild hoch, um die KI-Analyse zu beginnen",
    disclaimer: "Dieses KI-Screening-Tool ist zur Unterstützung der Früherkennung entwickelt, ersetzt aber keine professionelle medizinische Diagnose. Konsultieren Sie immer einen qualifizierten Gesundheitsexperten.",
    
    // Navigation
    home: "Startseite",
    about: "Über uns",
    resources: "Ressourcen",
    support: "Unterstützung",
    aboutBreastCancer: "Über Brustkrebs",
    donateMakeADifference: "Spenden – Einen Unterschied machen",
    educationalHub: "Bildungszentrum",
    livingWithBreastCancer: "Leben mit Brustkrebs",
    preventionScreening: "Vorbeugung & Vorsorge",
    treatmentOptions: "Behandlungsoptionen",
    resourcesSupport: "Ressourcen & Support",
    researchInnovation: "Forschung & Innovation",
    contactUs: "Kontakt",

    // Basic page translations
    aboutBreastCancerTitle: "Über Brustkrebs",
    aboutBreastCancerDescription: "Brustkrebs verstehen ist der erste Schritt zur Prävention und Früherkennung.",
    livingWithBreastCancerTitle: "Leben mit Brustkrebs",
    livingWithBreastCancerDescription: "Eine Brustkrebsdiagnose definiert Sie nicht.",
    preventionScreeningTitle: "Vorbeugung & Vorsorge",
    preventionScreeningDescription: "Früherkennung rettet Leben.",
    treatmentOptionsTitle: "Behandlungsoptionen",
    treatmentOptionsDescription: "Moderne Brustkrebsbehandlung bietet viele wirksame Optionen.",
    resourcesSupportTitle: "Ressourcen & Support",
    resourcesSupportDescription: "Umfassende Unterstützungsdienste für Ihren Weg.",
    researchInnovationTitle: "Forschung & Innovation",
    researchInnovationDescription: "Modernste Forschung verbessert ständig Erkennung und Behandlung.",
    contactUsTitle: "Kontakt",
    contactUsDescription: "Wir sind hier, um zu helfen.",
    learnMore: "Mehr Erfahren",
    getSupport: "Unterstützung Erhalten",
    readMore: "Weiterlesen",
    scheduleScreening: "Vorsorge Planen",
    sendMessage: "Nachricht Senden",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}